comment:
  image:
    repository: maksov/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: maksov/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: maksov/ui
    tag: latest
    service:
      externalPort: 9292