version: '3.3'

#Sevices
services:
 
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      management_net:
      back_net:
        aliases:
          - post_db
          - comment_db

  post:
    image: ${DOCKER_HUB_USERNAME}/post:${POST_TAG}
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      management_net:
      back_net:
      front_net:
        aliases:
          - post
    depends_on:
      - post_db

  comment:
    container_name: comment
    image: ${DOCKER_HUB_USERNAME}/comment:${COMMENT_TAG}
    networks:
      front_net:
      back_net:
      management_net:
    depends_on:
      - post_db

  ui:
    image: artemkin/ui
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - "9292:9292"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
        front_net:
        management_net:
    depends_on:
      - post
      - comment

  

        


#Volumes
volumes:
  post_db:
  
#Networks
networks:
  front_net:
  back_net:
  management_net:
    external: true


