apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      name: comment-pod
      labels:
        app: comment
    spec:
      containers:
      - image: maksov/comment
        name: comment
