apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      name: post-pod
      labels:
        app: post
    spec:
      containers:
      - image: maksov/post
        name: post